name: interns2025b_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  http: ^1.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:

  uses-material-design: true
  generate: true
  assets:
    - .env
    - ./assets/images/app_logo.png
