name: Test & analyze Flutter codebase

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test-and-analyze:
    name: Test & analyze Flutter codebase
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Copy environment
        run: cp .env.example .env

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Execute tests
        run: flutter test